### ISSUE TITLE
KeyError: 'gamma_detect_move'

### ISSUE THREAD

**Issue by r08922a10** [r08922a10/AI_Final#12]
```
Traceback (most recent call last):
  File "rl_reinforce.py", line 828, in <module>
    main()
  File "rl_reinforce.py", line 823, in main
    game.episodes(plot=False)
  File "rl_reinforce.py", line 767, in episodes
    state = self.environment.init_state()
  File "rl_reinforce.py", line 120, in init_state
    self._assert_all(if_config=True, if_seir=True)
  File "rl_reinforce.py", line 355, in _assert_all
    assert rule2(self._config[name])
KeyError: 'gamma_detect_move'
```

**Comment by r08922196** [comment]
加 `config.json`
