### ISSUE TITLE
Value error when setting max_steps=100

### ISSUE THREAD

**Issue by r08922a10** [r08922a10/AI_Final#8]
```python
def episodes(self, max_episodes=5, max_steps=100, plot=False):
```

```
Traceback (most recent call last):
  File "rl_reinforce.py", line 642, in <module>
    main()
  File "rl_reinforce.py", line 637, in main
    game.episodes(plot=True)
  File "rl_reinforce.py", line 600, in episodes
    state, reward, is_terminal = self.environment.step(state, action, t=t)
  File "rl_reinforce.py", line 259, in step
    EQ = np.random.binomial(self.E, self.gamma_detect * self._config['alpha_eq'])
  File "mtrand.pyx", line 3378, in numpy.random.mtrand.RandomState.binomial
  File "_common.pyx", line 352, in numpy.random._common.check_constraint
ValueError: n < 0
```

**Comment by r08922a27** [comment]
這個不是因為 max_step 問題，這個是在 E 的時候流出去太多噴到負數，儒正在修這個問題。

**Comment by r08922196** [comment]
I sent #9 to fix this issue
